# -*- coding: utf-8 -*-
"""Customer Churn Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NngDDnT8IRi4ehdWiUA_3mT9fmMQKq9J
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import warnings
warnings.filterwarnings("ignore")

sns.set_palette("Set2")       # ✅ every chart auto gets different colors

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head()

df.info()

# Replacing blanks with 0 as tenure is 0 and no total charges are recorded

df["TotalCharges"] = df["TotalCharges"].replace(" ", "0")
df["TotalCharges"] = df["TotalCharges"].astype("float")

df.info()

df.isnull()

df.isnull().sum().sum()

df.describe()

df["customerID"].duplicated().sum()

def conv(value):
  if value == 1:
    return "yes"
  else:
    return "no"

df['SeniorCitizen'] = df["SeniorCitizen"].apply(conv)

df.head(30)

"""# converted 0 and 1 values of senior citizen to yes/n to mkae it easier to understand"""

ax = sns.countplot(x = 'Churn', data = df)

ax.bar_label(ax.containers[0])
plt.title("Count of Customers by Churn")
plt.show()

gb = df.groupby("Churn").agg({'Churn':"count"})
plt.pie(gb['Churn'], labels = gb.index, autopct = "%.2f%%")
plt.title("% of Churned Customers")
plt.show()

#from the given pie chart we can conclude that 26.54% of our customers have churned out.
# now let's explore the reason behind it

sns.countplot(x = "gender", data = df, hue = "Churn")
plt.title("Count of Customers by Gender and Churn")
plt.show()

ax = sns.countplot(x = 'SeniorCitizen', data = df)

ax.bar_label(ax.containers[0])
plt.title("Count of Customers by Senior Citizen")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# ✅ Step 1 — calculate percentages
crosstab = pd.crosstab(df["SeniorCitizen"], df["Churn"], normalize="index") * 100

# ✅ Step 2 — plot stacked bar chart
ax = crosstab.plot(kind="bar",
                   stacked=True,
                   figsize=(8, 5),
                   color=["#4ECDC4", "#FF6B6B"],
                   edgecolor="white",
                   width=0.5)

# ✅ Step 3 — add percentage labels on each segment
for bar_stack in ax.containers:
    for bar in bar_stack:
        height = bar.get_height()
        if height > 1:                              # only label if segment is visible
            ax.text(
                bar.get_x() + bar.get_width() / 2, # x center
                bar.get_y() + height / 2,           # y center of segment
                f"{height:.1f}%",                   # label text
                ha="center", va="center",
                fontsize=11, fontweight="bold",
                color="white"
            )

plt.title("SeniorCitizen vs Churn — Stacked by Percentage",
          fontsize=13, fontweight="bold")
plt.xlabel("Senior Citizen (0 = No, 1 = Yes)")
plt.ylabel("Percentage (%)")
plt.xticks(rotation=0)
plt.legend(title="Churn", labels=["No Churn", "Churned"])
plt.tight_layout()
plt.show()

# Comparative a greated percentage of people in senior citizen category have churned

plt.figure(figsize=(12, 5))
ax = sns.histplot(x="tenure", data=df, bins=50, color="#2874A6")

# ✅ add data labels on each bar
for bar in ax.patches:
    height = bar.get_height()
    if height > 0:                                   # only label visible bars
        ax.text(
            bar.get_x() + bar.get_width() / 2,      # x center
            height + 0.3,                            # y position above bar
            f"{int(height)}",                        # label text
            ha="center", va="bottom",
            fontsize=7, fontweight="bold",
            color="#1A1A2E"
        )

plt.title("Distribution of Customer Tenure",
          fontsize=13, fontweight="bold")
plt.xlabel("Tenure (Months)")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

ax = sns.countplot(x = "Contract", data = df, hue = "Churn")

ax.bar_label(ax.containers[0])
plt.title("Count of Customers by Contract and Churn")
plt.show()

df.columns.values

cols = ['PhoneService', 'MultipleLines', 'InternetService',
        'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
        'TechSupport', 'StreamingTV', 'StreamingMovies']

plt.figure(figsize=(18, 15))

for i, col in enumerate(cols, 1):

    ax = plt.subplot(3, 3, i)

    sns.countplot(
        x=col,
        hue='Churn',          # ✅ Add churn comparison
        data=df,
        palette='Blues'
    )

    for container in ax.containers:
        ax.bar_label(container,
                     fontsize=8,
                     fontweight='bold',
                     padding=2)

    plt.title(f'{col} vs Churn',
              fontsize=11,
              fontweight='bold')

    plt.xlabel("")
    plt.ylabel("Count", fontsize=9)

    plt.xticks(rotation=15, fontsize=9)

plt.suptitle(
    "Service Features vs Churn Analysis",
    fontsize=18,
    fontweight='bold',
    y=1.02
)

plt.tight_layout()
plt.show()

ax = sns.countplot(
    x="PaymentMethod",
    data=df,
    hue="Churn"
)

# Add bar labels
for container in ax.containers:
    ax.bar_label(container)

# Title
plt.title("Count of Churned Customers by Payment Method",
          fontsize=14,
          fontweight='bold')

# X-axis label
plt.xlabel("Payment Method",
           fontsize=12,
           fontweight='bold')

# Y-axis label
plt.ylabel("Customer Count",
           fontsize=12,
           fontweight='bold')

# Rotate x labels for better visibility
plt.xticks(rotation=20)

plt.show()

